### ISSUE TITLE
Tiny request: change the placeholder color for various text inputs.

### ISSUE THREAD

**Issue by sjaakbanaan** [forest-host/support#13]
**Is your feature request related to a problem? Please describe.**
The placeholder color in CSS is white, just like normal texts. So the only way to find out if this text is pre-entered or not, is by clicking it:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/2773301/214348247-39d124e0-fda3-4c1a-8c0f-7936c42a560e.png">
I do know the background color changes with an actual value, but that's less intuitive than a grey placeholder text.

**Comment by mass-im** [comment]
Good one!
To be sure I'm understanding this correctly.
When a value is a placeholder: the current style is fine
When a value is the default it's confusing because it looks like the placeholder

To solve this we can do it like this:
- Placeholder: grey text
- Default value: white text (since it's a value)

Does that make sense?

**Comment by sjaakbanaan** [comment]
it does! And this sounds like a good solution :)

**Comment by Forest-Gio** [comment]
I've implemented a fix for this! Closing this issue
