### ISSUE TITLE
[BUG] cannot rename/delete folder in filebrowser

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#8]
**Describe the bug**
when renaming/delete the folder /web it throws an 503 error. this is likely due to the fact that the root is mounted. renaming a folder such as /uploads/2022 to /uploads/2022KAAS does work

**Include relevant information**
filebrowser id: ad0336d6-5a8a-4182-accc-aee6d423f150
php id: d2a0ef48-8046-49ce-98fb-34e9a092bcb4
uploads id: 1362

**To Reproduce**
1. set up an glemrock site
2. add the filebrowser 
3. in wordpress add an random image to the image gallary
4. go to filebrowser and try to change the name of /web

**Expected behavior**
the folder being renamed or only show the folders which i can edit

**Screenshots**

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by mass-im** [comment]
Thanks for letting us know! Will look into it.

**Comment by mass-im** [comment]
Hey @cvanh!

Dived a little deeper into this.
What you say is absolutely correct and intended. I thought it was about changing file and folder names (and it somewhat is). But yeah the folders you set as your mount path cannot be renamed.
We did this so that it is clear what volume is mounted.
In theory it is possible to connect multiple volumes. To prevent collisions and to keep clear what volume you interact with we put the volume at the path given.

This path can be changed in the blueprint editor at any time though. (keep in mind this impacts all services connected)

Let me know if you have any more fun questions!
